##
# Installs pre-requisites for ethercis/ehrservice (https://github.com/ethercis/ehrservice)
# This playbook originally copied from https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml
---
# install required libs for pgsql stuff
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: Add PostgreSQL repository
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present
  - name: Add PostgreSQL repository key
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - postgresql-9.6
        - libpq-dev
        - python-psycopg2
        # require for pgsql extensions to be installed
        - postgresql-server-dev-9.6
        - postgresql-contrib-9.6
        - pgxnclient
        - postgresql-common
        - git
        - flex
        - bison
  - name: ensure the temporal_tables pgsql extension is installed
    command: pgxn install temporal_tables

# build the pgsql jsquery extension
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: clone the repo
    command: git clone https://github.com/postgrespro/jsquery.git
    args:
      chdir: /home/vagrant
      creates: /home/vagrant/jsquery
  - name: make the extension
    command: make USE_PGXS=1
    args:
      chdir: /home/vagrant/jsquery
      creates: /home/vagrant/jsquery/jsquery.so
  - name: install the extension
    command: make USE_PGXS=1 install
    args:
      chdir: /home/vagrant/jsquery
      creates: /usr/lib/postgresql/9.6/lib/jsquery.so
  - name: allow postgres user access (to run regression checks)
    file:
      path: /home/vagrant/jsquery
      recurse: yes
      mode: "ugo+rw"

- hosts: all
  become: yes
  become_user: postgres
  gather_facts: no
  tasks:
  - name: check the extension is installed correctly
    command: make USE_PGXS=1 installcheck
    args:
      chdir: /home/vagrant/jsquery


# setup ehr database
- hosts: all
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: ethercis
    dbuser: ethercis
    dbpassword: ethercis
    extschema: ext

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ensure no other user can access the database
    postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent

  - name: create schema for extensions
    command: psql -c 'CREATE SCHEMA IF NOT EXISTS {{extschema}} AUTHORIZATION {{dbname}};' {{dbname}}

  - name: add extensions to schema
#    don't use postgresql_ext because it doesn't support creating extensions in schemas (only dbs)
    command: psql -c 'CREATE EXTENSION IF NOT EXISTS "{{item}}" SCHEMA {{extschema}};' {{dbname}}
    with_items:
        - uuid-ossp
        - temporal_tables
        - jsquery
        - ltree

  # setup the search_path so the extensions can be found
  - name: update database search_path
    command: psql -c 'ALTER DATABASE {{dbname}} SET search_path TO "$user",public,{{extschema}};' {{dbname}}
  - name: grant access to functions
    command: psql -c 'GRANT ALL ON ALL FUNCTIONS IN SCHEMA {{extschema}} TO {{dbuser}};' {{dbname}}

# end of pgsql, now build / install the ehrservice itself
# install required libs for build stuff
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: Add gradle repository
    apt_repository: repo='ppa:cwchien/gradle' state=present      # note this is an unsupported repo
  - name: Add jdk repository
    apt_repository: repo='ppa:webupd8team/java' state=present      # note this is an unsupported repo
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: Automatically select the Oracle License
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - oracle-java8-set-default
        - gradle
        - maven

# build ehrservice
- hosts: all
  become: no
  gather_facts: no
  tasks:
    - name: build the ehrservice artifacts
      command: gradle build
      args:
        chdir: /vagrant

